# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  # These are set in order to pass the flake check
  boot.loader.grub.devices = [ "/dev/null" ];
  fileSystems."/" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

}
