# This file was generated by go2nix.
{
  lib,
  buildGoModule,
  fetchFromGitLab,
  installShellFiles,
}:

buildGoModule rec {
  pname = "machine";
  version = "0.16.2-gitlab.29";

  src = fetchFromGitLab {
    rev = "v${version}";
    owner = "gitlab-org/ci-cd";
    repo = "docker-machine";
    hash = "sha256-qX+rHQBFzODuH+h3d+84jqj7dpGcg3PPYD+Smd2xdwc=";
  };

  doCheck = false;

  vendorHash = "sha256-apI1wUm/idIxsmGgB1bazsVGfAVjEodxd9+UTDhKiPA=";

  nativeBuildInputs = [ installShellFiles ];

  postInstall = ''
    pushd contrib/completion
    installShellCompletion --bash bash/*
    installShellCompletion --zsh zsh/*
    popd
  '';

  meta = with lib; {
    homepage = "https://docs.docker.com/machine/";
    description = "Docker Machine is a tool that lets you install Docker Engine on virtual hosts, and manage Docker Engine on the hosts";
    license = licenses.asl20;
    maintainers = with maintainers; [
      offline
      tailhook
    ];
    platforms = platforms.unix;
  };
}
